* Community Energy Map
A web-based map which shows the Rural (RCEF) and Urban (UCEF) areas eligible for the Community Energy Fund in the United Kingdom.

Uses the [[http://leafletjs.com/][Leaflet]] library to display an Open Street Map base layer. Overlays it with tiles showing the UCEF and RCEF areas.

Search for a location (for example, a postcode) using the search box, then hover the mouse over the map to see the rural or urban status.
 
** Source Code
[[https://github.com/cse-bristol/community-energy-fund-map][Source code]] provided under an open-source MIT license.

This project was forked from the open source mapping tool developed for the STEEP project at git@csesvn.git.beanstalkapp.com:/csesvn/open-data-map.git.

** Installation
To install, clone the repository then serve using any web server, for example using python3 on a Debian system:
#+BEGIN_SRC sh
  sudo python3 -m http.server 80 &
#+END_SRC

*** Building the Tiles
The tiles are not included in the source code repository as they are too large. The shapefiles from which they are generated are, however.

To generate the tiles, you will need the following:
 * make
 * Python 2.7+
 * mapnik
 * mapnik Python bindings.

On a Debian based system, these are available as apt packages:
#+BEGIN_SRC sh
  -- python and make are probably already installed
  -- sudo aptitude install make
  -- sudo aptitude install python
  sudo aptitude install libmapnik-dev
  sudo aptitude install python-mapnik
#+END_SRC

Having installed these, run:
#+BEGIN_SRC sh
  make tiles
#+END_SRC

*** Building the Code
This step is only necessary if you make changes to the code. Our Javascript files our arranged as node.js modules, and we use the 'browserify' tool to combine them into a single file.

Begin by installing [[http://nodejs.org/][Node JS]]. On a Debian-based system, I'd recommend using this PPA:
#+BEGIN_SRC sh
sudo add-apt-repository ppa:chris-lea/node.js 
sudo aptitude update
sudo aptitude install -y nodejs
#+END_SRC

Then run the following:
#+BEGIN_SRC sh
  npm -g install browserify # Install Browserify as a command you can run.
  make
#+END_SRC
