* Community Energy Map
A web-based map which shows the Rural and Urban areas eligible for the Community Energy Fund in the United Kingdom.

Uses the [[http://leafletjs.com/][Leaflet]] library to display an Open Street Map base layer. Overlays it with a tile layer.

Search for a location (for example, a postcode) using the search box, then hover the mouse over the map to see the rural or urban status.
 
** Source Code
[[https://github.com/cse-bristol/community-energy-fund-map][Source code]] provided under an open-source MIT license.

This project was forked from the open source mapping tool developed for the STEEP project at git@csesvn.git.beanstalkapp.com:/csesvn/open-data-map.git.

** Installation
To install, clone the repository then serve using any web server, for example using python3 on a Debian system:
#+BEGIN_SRC sh
  sudo python3 -m http.server 80 &
#+END_SRC

*** Building the Code
If you make changes to the code, you will need to rebuild it. Our Javascript files our arranged as node.js modules, and we use the 'browserify' tool to combine them into a single file.

Begin by installing [[http://nodejs.org/][Node JS]]. On a Debian-based system, I'd recommend using this PPA:
#+BEGIN_SRC sh
sudo add-apt-repository ppa:chris-lea/node.js 
sudo aptitude update
sudo aptitude install -y nodejs
#+END_SRC

Then run the following:
#+BEGIN_SRC sh
  npm -g install browserify # Install Browserify as a command you can run.
  make
#+END_SRC
